IsolationZero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from IsolationZero import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")), 
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views 

app_name = "blog"
urlpatterns=[
    path("", views.index, name = "index"),
    # path("about/", views.about, name = "about"),
    path("factors/", views.factors, name = "factors"),
    path("method/", views.method, name = "method"),
    path("how/", views.how, name = "how"),
    path("references/", views.references, name = "references"),
    path("env/", views.env, name = "env"),
    
    # path("factors/ages", views.ages, name = "ages"),
    path("factors/group", views.group, name = "group"),
    path("factors/metropolitan", views.metropolitan, name = "metropolitan"),
    path("factors/single", views.single, name = "single"),
    path("factors/spouse", views.spouse, name = "spouse"),

    path("factors/job", views.job, name = "job"),
    path("factors/place", views.place, name = "place"),

    # path('chart/', views.year_show_chart, name='show_chart'),
    # 차트 삽입 about
    path('about/', views.year_chart_about, name='about'),
    # 차트 삽입 factors/ages
    path('factors/ages/', views.factors_age_chart, name='ages'),
] 

blog/models.py
from django.db import models

# Create your models here.

IsolationZero/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request): 
    return render(request, "index.html")

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
import pandas as pd
import plotly.express as px
import plotly.graph_objs as go
import plotly.io as pio


# Create your views here.
# 기본 페이지
def index(request): 
    return render(request, "index.html")

# 분석배경
# def about(request): 
#     return render(request, "about.html")

# 분석방법
def method(request): 
    return render(request, "method.html")

# 관련요인
def factors(request): 
    return render(request, "factors.html")

# how
def how(request): 
    return render(request, "how.html")

# references
def references(request): 
    return render(request, "references.html")

# 개발환경
def env(request): 
    return render(request, "env.html")



# FACTORS/ 
# 연령대
# def ages(request): 
#     return render(request, "factors/ages.html")

# FACTORS/ 
# 단체참여
def group(request): 
    return render(request, "factors/group.html")

# FACTORS/
# 수도권
def metropolitan(request): 
    return render(request, "factors/metropolitan.html")

# FACTORS/
# 1인가구
def single(request): 
    return render(request, "factors/single.html")

# FACTORS/ 
# 배우자
def spouse(request): 
    return render(request, "factors/spouse.html")

# FACTORS/ 
# 직업
def job(request): 
    return render(request, "factors/job.html")

# FACTORS/ 
# 배우자
def place(request): 
    return render(request, "factors/place.html")


# 년도별 chart - about 에 넣기 

def year_chart_about(request) : 
    df = pd.read_csv("data/graph.csv")

    fig = px.bar(df, x="age", y= "isolation", 
             barmode="group",
             animation_frame="year",
             text_auto=True,  #글자 설정
             width = 600, 
             height = 500             
             )
    graph_html = fig.to_html(full_html=False)

    return render(request, 'about.html', {"graph_html" : graph_html})


# 년도별 ages

def factors_age_chart(request) : 
    df = pd.read_csv("data/age_chart.csv")

    fig = px.bar(df, 
                x="연령대", 
                y= "percent", 
                # barmode="group",             
                text_auto=".3s",  #글자 설정
                color = "연령대",
                width = 1000, 
                height = 500,    
                # title = "2017~2023 연령대별 사회적고립도 "
                )
                
    # fig.update_yaxes(range=[10, 30])
    graph_html = fig.to_html(full_html=False)

    return render(request, 'factors/ages.html', {"graph_html" : graph_html})

blog/templates/chart.html
<html lang="en">
    <head>
        <!-- basic -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- mobile metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="initial-scale=1, maximum-scale=1">
        <!-- site metas -->
        <title>고립탈출 대작전</title>
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- <link rel="stylesheet" href="/static/css/test.css"> -->
        <!-- bootstrap css -->
        <!-- <link rel="stylesheet" href="./css/bootstrap.min.css"> -->
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
        <!-- style css -->
        <link rel="stylesheet" href="/static/css/style.css">
        <!-- Responsive-->
        <link rel="stylesheet" href="/static/css/responsive.css">
  
        <!-- Scrollbar Custom CSS -->
        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
         <link rel="stylesheet" href="/static/css/owl.carousel.min.css"> 
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
        <link rel="stylesheet" href="https://rawgit.com/LeshikJanz/libraries/master/Bootstrap/baguetteBox.min.css">
        
        <!-- 차트 -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
     </head>
     <!-- body -->
     <body class="main-layout">
        <!-- top -->
           <!-- header -->    
           <!-- navbar -->
           <nav class="site-navbar ">
              <div class="container-fluid">
                 <a class="navbar-brand" href="/">IsolationZero</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                    </button>               
                 <ul>
                    <li class="nav-item">
                          <a class="nav-link" href="{% url 'blog:about' %}">분석배경</a>
                    </li>
  
                    <li class="nav-item">
                       <a class="nav-link" href="{% url 'blog:method' %}">분석방법</a>
                    </li>
  
                    <li class="nav-item dropdown">
                       <a class="nav-link dropdown-toggle" href="{% url 'blog:factors' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                         관련요인
                       </a>
                       <ul class="dropdown-menu">
                         <li><a class="dropdown-item" href="{% url 'blog:ages' %}">연령대</a></li>
                         <li><a class="dropdown-item" href="{% url 'blog:group' %}">단체참여</a></li>                       
                         <li><a class="dropdown-item" href="{% url 'blog:spouse' %}">배우자</a></li>                       
                         <li><a class="dropdown-item" href="{% url 'blog:single' %}">1인가구</a></li>
                         <li><a class="dropdown-item" href="{% url 'blog:metropolitan' %}">지역</a></li>
                         
                       </ul>
                     </li>
  
  
                    <li class="nav-item">
                          <a class="nav-link" href="{% url 'blog:how' %}">How</a>
                    </li>
  
                    <li class="nav-item">
                          <a class="nav-link" href="{% url 'blog:references' %}">references</a>
                    </li>
  
                    <li class="nav-item">
                          <a class="nav-link" href="{% url 'blog:env' %}">개발환경</a>
                    </li>
                 </ul>
                 <hr>
              </div>        
           </nav>
        <div class="full_bg"></div>
        <!-- nav 끝  -->
    <!-- <div class="coronata">
        <div class="container">  -->
    <script type='module' src='https://prod-apnortheast-a.online.tableau.com/javascripts/api/tableau.embedding.3.latest.min.js'></script><tableau-viz id='tableau-viz' src='https://prod-apnortheast-a.online.tableau.com/t/jadeym1222-d9df37245f/views/_0/Dashboard1' width='1600' height='940' hide-tabs toolbar='bottom' ></tableau-viz>
        <!-- </div>
    </div> -->
</body>
</html>

blog/templates/env.html
<!DOCTYPE html>
    <html lang="ko">
        <head>
           <!-- basic -->
           <meta charset="utf-8">
           <meta http-equiv="X-UA-Compatible" content="IE=edge">
           <!-- mobile metas -->
           <meta name="viewport" content="width=device-width, initial-scale=1">
           <meta name="viewport" content="initial-scale=1, maximum-scale=1">
           <!-- site metas -->
           <title>고립탈출 대작전</title>
           <meta name="keywords" content="">
           <meta name="description" content="">
           <meta name="author" content="">
           <!-- <link rel="stylesheet" href="/static/css/test.css"> -->
           <!-- bootstrap css -->
           <!-- <link rel="stylesheet" href="./css/bootstrap.min.css"> -->
           <link rel="stylesheet" href="/static/css/bootstrap.min.css">
           <!-- style css -->
           <link rel="stylesheet" href="/static/css/style.css">
           <!-- Responsive-->
           <link rel="stylesheet" href="/static/css/responsive.css">
           <!-- fevicon -->
           <link rel="icon" href="images/fevicon.png" type="image/gif" />
           <!-- Scrollbar Custom CSS -->
           <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
            <link rel="stylesheet" href="/static/css/owl.carousel.min.css"> 
           <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
           <link rel="stylesheet" href="https://rawgit.com/LeshikJanz/libraries/master/Bootstrap/baguetteBox.min.css">
           
           <!--[if lt IE 9]>
           <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
           <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
        </head>
        <!-- body -->
        <body class="main-layout">
           <!-- top -->
              <!-- header -->

         <!-- navbar -->
         <nav class="site-navbar ">
            <div class="container-fluid">
               <a class="navbar-brand" href="/">IsolationZero</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                  </button>               
               <ul>
                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:about' %}">분석배경</a>
                  </li>

                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'blog:method' %}">분석방법</a>
                  </li>

                  <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="{% url 'blog:factors' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                       관련요인
                     </a>
                     <ul class="dropdown-menu">
                       <li><a class="dropdown-item" href="{% url 'blog:ages' %}">연령대</a></li>
                       <li><a class="dropdown-item" href="{% url 'blog:group' %}">단체참여</a></li>                       
                       <li><a class="dropdown-item" href="{% url 'blog:spouse' %}">배우자</a></li>                       
                       <li><a class="dropdown-item" href="{% url 'blog:single' %}">1인가구</a></li>
                       <li><a class="dropdown-item" href="{% url 'blog:metropolitan' %}">지역</a></li>
                       
                     </ul>
                   </li>


                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:how' %}">How</a>
                  </li>

                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:references' %}">references</a>
                  </li>

                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:env' %}">개발환경</a>
                  </li>
               </ul>
               <hr>
            </div>        
         </nav>
      <div class="full_bg"></div>
      <!-- nav 끝  -->
    <h1>env</h1>
    <div class="coronata">
      <div class="container">                  
         <div class="titlepage text_align_left">
            개발환경
         </div>  
      </div>          
    </div>
</body>
</html>

blog/templates/factors.html
<!DOCTYPE html>
<html lang="ko">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>고립탈출 대작전</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- <link rel="stylesheet" href="/static/css/test.css"> -->
      <!-- bootstrap css -->
      <!-- <link rel="stylesheet" href="./css/bootstrap.min.css"> -->
      <link rel="stylesheet" href="/static/css/bootstrap.min.css">
      <!-- style css -->
      <link rel="stylesheet" href="/static/css/style.css">
      <!-- Responsive-->
      <link rel="stylesheet" href="/static/css/responsive.css">
      <!-- fevicon -->
      <link rel="icon" href="images/fevicon.png" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
       <link rel="stylesheet" href="/static/css/owl.carousel.min.css"> 
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <link rel="stylesheet" href="https://rawgit.com/LeshikJanz/libraries/master/Bootstrap/baguetteBox.min.css">
      
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout">
      <!-- top -->
         <!-- header -->

         <!-- navbar -->
         <nav class="site-navbar ">
            <div class="container-fluid">
               <a class="navbar-brand" href="/">IsolationZero</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                  </button>               
               <ul>
                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:about' %}">분석배경</a>
                  </li>

                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'blog:method' %}">분석방법</a>
                  </li>

                  <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="{% url 'blog:factors' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                       관련요인
                     </a>
                     <ul class="dropdown-menu">
                       <li><a class="dropdown-item" href="{% url 'blog:ages' %}">연령대</a></li>
                       <li><a class="dropdown-item" href="{% url 'blog:group' %}">단체참여</a></li>                       
                       <li><a class="dropdown-item" href="{% url 'blog:spouse' %}">배우자</a></li>                       
                       <li><a class="dropdown-item" href="{% url 'blog:single' %}">1인가구</a></li>
                       <li><a class="dropdown-item" href="{% url 'blog:metropolitan' %}">지역</a></li>
                       
                     </ul>
                   </li>
            


                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:how' %}">How</a>
                  </li>

                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:references' %}">references</a>
                  </li>

                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:env' %}">개발환경</a>
                  </li>
               </ul>
               <hr>
            </div>        
         </nav>      
      <!-- nav 끝  -->
               
   
      <!-- 메인 내용 -->
      <div class="about">
         <div class="container">
            <div class="row d_flex grid">
               <div class="col-md-12 oder1">


                  <div class="titlepage text_align_left">                     
                    
                     <p>
                         <strong>노년층의 사회적 고립</strong>이 심각한 수준에 있다는 것을 여러 측면에서 확인했습니다.<br><br>

                         사회적 고립은 단순히 사회적 상호작용의 부족을 의미하는 것이 아니라, <strong>정신적 및 신체적 건강</strong>에 
                         직접적인 영향을 미치는 중요한 요인입니다.<br><br>
                         사회적 고립이 특히 혼인상태가 미상인 노년층에서 높은 심혈관 질환 사망률과 연관되어 있음을 
                         확인했으며, 수도권과 비수도권 모두에서 이러한 경향이 나타났습니다.
                     </p>
                     
                     <h2>관련요인 분석 결과 요약</h2>
                     <p>
                         1. <strong>연령대별 분석</strong>에서, 연령대가 높아질수록 사회적 고립도가 증가하는 경향이 뚜렷하게 나타났습니다. 
                         특히 노년층이 가장 높은 사회적 고립도를 보였습니다.<br><br>
                         2. <strong>가구유형별 분석</strong>에서는 1인 가구가 비 1인 가구보다 더 높은 사회적 고립도를 느끼는 것으로 
                         확인되었습니다.<br><br>
                         3. <strong>단체 참여 여부에 따른 분석</strong>에서는, 단체에 참여하지 않는 그룹이 참여하는 그룹에 비해 
                         고립도가 더 높았습니다.<br><br>
                         4. <strong>배우자 유무에 따른 분석</strong>에서, 배우자가 없는 노년층이 배우자가 있는 노년층에 비해 
                         고립도가 더 높았습니다.<br><br>
                         5. <strong>사망원인통계 </strong>(배우자, 지역, 사망장소, 직업)를 통해 심혈관 질환과 인지 장애가 사회적 고립과 밀접한 관련이 있음을 확인했습니다. 
                         특히, 수도권/비수도권의 혼인상태 미상인 노년층에서 그 영향이 두드러졌습니다.
                     </p>
                     
                     
                  </div>                  

                  
               </div>
            </div>
         </div>
      </div>

      <!-- factors 페이지네이션 (페이지 연결하고 수정 예정) -->
   </div>
   <div class="protect_bg">
      <div class="container">
         
         <div class="row">
            <div class="col-md-12">
               <div class="titlepage text_align_center">
               <hr>
               <h3>관련 요인</h3>
               
               <hr>
               <!--  Demos -->
               <div class="owl-carousel owl-theme">
                  <div class="item">
                     <div class="protect_box text_align_center">
                     <div class="desktop">
                        <i><img src="https://images.pexels.com/photos/3823542/pexels-photo-3823542.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="#"/></i>
                        <h4> <br>연령대별 </h4>
                        <div class = "word"> Erikson의 이론에 따르면, 노년기에 고립은 절망감을 증가시킬 수 있습니다. 우리의 결과는 이 이론을 지지하며, 노년층의 고립도 문제를 심각하게 받아들여야 합니다.</div>
                     </div>
                        <a class="read_more" href="{% url 'blog:ages' %}">Read More</a>
                     </div>
                  </div>
                  <div class="item">
                     <div class="protect_box text_align_center">
                     <div class="desktop">
                        <i><img src="https://images.pexels.com/photos/8861582/pexels-photo-8861582.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="#"/></i>
                        <h4> <br>1인가구 vs 비1인가구</h4>                                 
                        <div class = "word"> Cohen의 연구에 따르면, 사회적 지지 부족은 스트레스를 증대시키고 건강을 악화시킬 수 있습니다. 1인가구 노년층의 고립도 문제를 해결하려면, 이들을 위한 사회적 지지망 구축이 필요합니다</div>
                     </div>
                        <a class="read_more" href="{% url 'blog:single' %}">Read More</a>
                     </div>
                  </div>
                  <div class="item">
                     <div class="protect_box text_align_center">
                     <div class="desktop">
                        <i><img src="https://images.pexels.com/photos/5713612/pexels-photo-5713612.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="#"/></i>
                        <h4> <br>단체참여 여부</h4>
                        <div class = "word"> Deci와 Ryan의 자기결정 이론에 따르면, 관계성 욕구는 심리적 건강에 매우 중요합니다. 단체 참여는 이러한 욕구를 충족시킴으로써 고립도를 줄일 수 있습니다</div>
                     </div>
                        <a class="read_more" href="{% url 'blog:group' %}">Read More</a>
                     </div>
                  </div>
                  <div class="item">
                     <div class="protect_box text_align_center">
                        <div class="desktop">
                           <i><img src="https://images.pexels.com/photos/8972578/pexels-photo-8972578.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load" alt="#"/></i>
                           <h4> <br>배우자 유무</h4>
                           <div class = "word"> Cacioppo의 연구에 따르면, 고독은 신체적, 정신적 건강을 해칠 수 있습니다. 배우자가 없는 노년층에 대한 추가적인 사회적 지원이 절실합니다</div>
                        </div>
                           <a class="read_more" href="{% url 'blog:spouse' %}">Read More</a>
                     </div>
                  </div>
                  <div class="item">
                     <div class="protect_box text_align_center">
                        <div class="desktop">
                           <i><img src="https://images.pexels.com/photos/5613942/pexels-photo-5613942.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="#"/></i>
                        <h4> <br>지역적 요인</h4>
                        <div class = "word">Masten의 연구에 따르면, 회복력은 역경을 극복하는 데 중요한 요소입니다. 지역사회 자원과 지지망이 노년층의 건강과 고립도에 영향을 미칠 수 있습니다</div>
                        </div>
                     <a class="read_more" href="{% url 'blog:metropolitan' %}">Read More</a>
                  </div>
               </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
</div>
<!-- factors 페이지네이션 끝-->

      </div>
      <!-- 빈공간 -->
          <!-- 빈공간 -->
   <div class="update">
      <div class="cevery_white">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2> </h2>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
   </div>
   <!-- 빈공간 -->
      <!--  footer -->
      <footer>
         <div class="footer">            
            <div class="copyright">
               <div class="container">
                  <div class="row">
                     <div class="col-md-8 offset-md-2">
                        <p>© 2020 All Rights Reserved. Design by <a href="https://html.design/"> Free html Templates</a></p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="/static/js/jquery.min.js"></script>
      <script src="/static/js/bootstrap.bundle.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
      <script src="/static/js/owl.carousel.min.js"></script>
      <script src="/static/js/custom.js"></script>
   </body>
</html>